import type { Metadata } from 'next';
import GuideArticle from '../../components/GuideArticle';

export const metadata: Metadata = {
  title: 'How to Reduce Image Size for Online Forms | TargetKB',
  description: 'Reduce photos for online forms without upload errors. Check the file size, dimensions, aspect ratio, and format before submitting.',
  alternates: { canonical: '/guides/reduce-image-size-for-online-forms' },
};

export default function Page() { return <GuideArticle label="Online form guide" title="How to reduce image size for online forms" intro="Online forms often reject a perfectly good image because it is a few kilobytes too large, the dimensions are wrong, or the file type is not accepted. This checklist helps you fix the actual cause instead of repeatedly trying random compression settings." sections={[{ heading: 'Read the requirement before changing the photo', body: <><p>Look for four things: maximum file size, required dimensions, aspect ratio, and accepted file format. “Under 100KB” is different from “exactly 100KB”, while “600 × 600 pixels” is a separate requirement from file size.</p><p>For a typical strict limit, start with the <a href="/compress-image-for-online-form">online form image compressor</a>.</p></> }, { heading: 'Set dimensions when the form asks for them', body: <><p>Many passport, visa, job, and registration portals require a square photo. Use a centered square crop and then resize to the stated dimensions. Do not stretch the image, because it can distort a face or document.</p><p>TargetKB includes a <a href="/resize-passport-photo">passport photo resize tool</a> and a <a href="/resize-photo-for-visa-application">visa photo workflow</a> for common use cases.</p></> }, { heading: 'Compress to a safe buffer', body: <><p>If the form allows a maximum of 100KB, aim a little below the limit rather than exactly at it. A safety buffer helps avoid a rejection caused by metadata or how the form measures the file.</p><p>Open <a href="/compress-image-to-100kb">Compress Image to 100KB</a> and download the optimized JPG after checking that the result looks clear.</p></> }, { heading: 'Use the format the form accepts', body: <><p>JPG is usually the best choice for a photograph when a strict file size is involved. PNG can be a better choice for text-heavy screenshots or transparency, but it is often larger. If the form accepts JPG, use <a href="/convert-image-to-jpg">Convert Image to JPG</a> before you compress a large photo.</p></> }, { heading: 'Check these four things before upload', body: <><ol><li>The file is below the stated maximum.</li><li>The width, height, and aspect ratio match the requirement.</li><li>The file uses an accepted type such as JPG or PNG.</li><li>The final preview is clear enough to identify the subject or read the required details.</li></ol><p>If the portal still refuses the file, download a fresh result from the original photo rather than compressing the already-compressed download again.</p></> }]} />; }
