import type { Metadata } from 'next';
import ExactSizeLanding from '../components/ExactSizeLanding';

export const metadata: Metadata = {
  title: 'Compress Images for WordPress | TargetKB',
  description: 'Compress WordPress images before upload. Resize to the display size, then target 200KB or set an exact size for lighter media files.',
  alternates: { canonical: '/compress-image-for-wordpress' },
};

export default function Page() { return <ExactSizeLanding size="200KB" query="200" title="Compress images for WordPress" description="Prepare smaller WordPress media files before upload. Resize to the display size first, then start with a 200KB target for ordinary content images." uses={[{ heading: 'Blog and featured images', text: 'Create lighter JPGs for articles, category pages, and featured-image uploads.' }, { heading: 'Media library uploads', text: 'Reduce file weight before adding several images to your WordPress library.' }, { heading: 'Product photos', text: 'Keep WooCommerce product images practical without sending full-size camera originals.' }]} guide="For most WordPress images, choose the dimensions your layout actually displays before compressing. A 200KB target is a practical starting point for ordinary content images; use more room for large hero photos and less for thumbnails. TargetKB can process up to 10 images at once." relatedGuide={{ href: '/guides/how-to-compress-images-for-wordpress', label: 'Read the full guide: how to compress images for WordPress' }} faqs={[{ question: 'Is 200KB right for every WordPress image?', answer: 'It is a practical starting point for ordinary content images. Large hero photos may need more detail, while thumbnails and small cards can use less.' }, { question: 'Should I resize before compressing a WordPress image?', answer: 'Yes. Resize close to the largest display size in your layout before compression. This avoids uploading pixels the website will not show.' }, { question: 'Can I use WebP for WordPress images?', answer: 'If your WordPress setup and theme support WebP, it can be a useful web format. JPG remains a widely compatible choice for photographs.' }, { question: 'Can I compress multiple WordPress images at once?', answer: 'Yes. Upload up to 10 images and apply the same target to each file.' }]} />; }
