import type { Metadata } from 'next';
import ExactSizeLanding from '../components/ExactSizeLanding';

export const metadata: Metadata = {
  title: 'Compress Images for Email Attachments | TargetKB',
  description: 'Compress up to 10 JPG, PNG, WebP, or HEIC images for email attachments. Start at 1MB per image or set an exact KB or MB target.',
  alternates: { canonical: '/compress-image-for-email' },
};

export default function Page() { return <ExactSizeLanding size="1 MB" query="1mb" title="Compress images for email attachments" description="Make photos easier to send by email. Start with a 1MB target per image, or enter the exact attachment size you need." uses={[{ heading: 'Smaller attachments', text: 'Reduce photo size before attaching files to a message.' }, { heading: 'Up to 10 images', text: 'Prepare a small batch of photos for one email without processing them one by one.' }, { heading: 'Clearer photo sharing', text: 'Keep enough detail for everyday images while avoiding needlessly heavy attachments.' }]} guide="Start with 1MB per image for everyday photo sharing. If you are sending several images, choose a lower target for each file so the full email stays manageable. TargetKB optimizes each image locally in your browser and preserves its aspect ratio." relatedGuide={{ href: '/guides/how-to-compress-images-for-email', label: 'Read the full guide: how to compress images for email' }} faqs={[{ question: 'What image size should I use for email?', answer: 'About 500KB to 1MB per everyday photo is a useful starting range. For several attachments, use a lower target for each image and check your email provider’s total attachment limit.' }, { question: 'Can I compress multiple images for one email?', answer: 'Yes. Upload up to 10 images, then download each optimized file before attaching them to your message.' }, { question: 'Will compressing an image make it look blurry?', answer: 'TargetKB searches for the clearest JPG result that fits your chosen file-size limit. Start with a sensible target and lower it only when you need a smaller attachment.' }]} />; }
