import type { Metadata } from 'next';
import ExactSizeLanding from '../components/ExactSizeLanding';

export const metadata: Metadata = {
  title: 'Compress Image for Online Forms | TargetKB',
  description: 'Make a photo fit an online form’s exact KB limit. Resize, crop, and convert JPG, PNG, WebP, or HEIC images privately in your browser.',
  alternates: { canonical: '/compress-image-for-online-form' },
};

export default function Page() { return <ExactSizeLanding size="100KB" query="100" title="Compress images for online forms" description="Fix a photo that an online form rejects for being too large. Start at 100KB, or set the exact limit shown by the form." uses={[{ heading: 'Registration forms', text: 'Create an upload-ready photo before submitting a registration or account form.' }, { heading: 'Exact KB limits', text: 'Work from the maximum file size shown by the form instead of guessing a quality setting.' }, { heading: 'Dimensions and crop', text: 'Meet pixel dimensions and square-photo requirements before you upload.' }]} guide="First check the form’s maximum file size, accepted format, and required dimensions. Then enter the stated limit, resize or crop only when needed, and download a JPG that is ready to upload. For a strict “under 100KB” rule, leave a little room below the limit." relatedGuide={{ href: '/guides/reduce-image-size-for-online-forms', label: 'Read the checklist: reduce image size for online forms' }} faqs={[{ question: 'Can I set an exact custom file-size target?', answer: 'Yes. Enter any target in KB or MB, then TargetKB finds the clearest result below that limit.' }, { question: 'What should I check when an online form rejects my image?', answer: 'Check the maximum file size, width and height, aspect ratio, and accepted file type. Any one of these can cause an upload failure.' }, { question: 'Should I use JPG or PNG for an online form?', answer: 'Use the format the form accepts. JPG is usually the smaller choice for photographs, while PNG may be useful for screenshots or images that need transparency.' }, { question: 'Are photos uploaded to TargetKB?', answer: 'Processing happens locally in your browser whenever your device supports it.' }]} />; }
