import type { MetadataRoute } from 'next';

export default function sitemap(): MetadataRoute.Sitemap {
  const base = 'https://targetkb.com';
  return [
    { url: `${base}/guides/image-compression-limits`, changeFrequency: 'monthly', priority: 0.8 },
    { url: base, changeFrequency: 'weekly', priority: 1 },
    { url: `${base}/compress-image-to-100kb`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/compress-image-to-50kb`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/compress-image-to-20kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-30kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-40kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-60kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-80kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-150kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-300kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-2mb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-200kb`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/compress-image-to-500kb`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-to-1mb`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/convert-heic-to-jpg`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/resize-image`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/resize-image-for-website`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/resize-image-for-wordpress`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/reduce-image-size-for-online-form`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/resize-passport-photo`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/resize-photo-for-visa-application`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/resize-photo-for-job-application`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/convert-image-to-jpg`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/image-converter`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/convert-png-to-jpg`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/convert-image-to-webp`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/convert-jpg-to-png`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/crop-image-to-square`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/compress-image-for-email`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/compress-image-for-wordpress`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/compress-image-for-job-application`, changeFrequency: 'weekly', priority: 0.85 },
    { url: `${base}/compress-image-for-online-form`, changeFrequency: 'weekly', priority: 0.9 },
    { url: `${base}/compress-image-for-discord`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-for-gmail`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/compress-image-for-whatsapp`, changeFrequency: 'weekly', priority: 0.8 },
    { url: `${base}/guides/compress-image-without-losing-quality`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/guides/how-to-compress-image-to-100kb`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/how-to-compress-image-to-150kb`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-compress-image-to-200kb`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/how-to-compress-jpeg-to-80kb`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-convert-image-to-jpg`, changeFrequency: 'monthly', priority: 0.9 },
    { url: `${base}/guides/how-to-compress-images-to-1mb`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-compress-images-for-email`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-compress-images-for-wordpress`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-compress-photo-for-job-application`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/how-to-compress-images-for-discord`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/guides/how-to-compress-photo-to-500kb`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/reduce-image-size-for-online-forms`, changeFrequency: 'monthly', priority: 0.85 },
    { url: `${base}/guides/best-image-sizes-for-email-websites-discord-and-job-applications`, changeFrequency: 'monthly', priority: 0.8 },
    { url: `${base}/privacy`, changeFrequency: 'yearly', priority: 0.3 },
    { url: `${base}/terms`, changeFrequency: 'yearly', priority: 0.3 },
  ];
}
