import type { Metadata } from 'next';
import ExactSizeLanding from '../components/ExactSizeLanding';

export const metadata: Metadata = {
  title: 'Compress Photo for Job Applications | TargetKB',
  description: 'Make a profile photo fit a job application or recruitment portal. Resize, square-crop, and compress to an exact KB or MB limit online.',
  alternates: { canonical: '/compress-image-for-job-application' },
};

export default function Page() { return <ExactSizeLanding size="100KB" query="100" title="Compress a photo for a job application" description="Fix a profile photo that a recruitment portal rejects for being too large. Start at 100KB, then adjust to the exact file limit and dimensions requested." uses={[{ heading: 'Career portals', text: 'Prepare a clear profile photo for job, recruitment, and applicant-tracking systems.' }, { heading: 'Exact upload limits', text: 'Start at 100KB or use the precise KB or MB maximum shown by the portal.' }, { heading: 'Square profile photos', text: 'Create a centered square crop when the application requires a specific photo shape.' }]} guide="Read the portal’s requirements first: maximum file size, accepted format, dimensions, and aspect ratio. For many headshots, 100KB and a square crop are useful starting points, but the portal’s instructions always come first. TargetKB keeps the aspect ratio unless you choose to crop." relatedGuide={{ href: '/guides/how-to-compress-photo-for-job-application', label: 'Read the full guide: prepare a photo for a job application' }} faqs={[{ question: 'What photo size should I use for a job application?', answer: 'Use the job portal’s stated requirements. If it gives no file size, a clear square JPG around 100KB is a practical starting point for a profile photo.' }, { question: 'Can I crop my photo to a square?', answer: 'Yes. Use the square-crop option before compressing when the application asks for a square photo.' }, { question: 'Can I use a phone photo for a job application?', answer: 'Yes, if it meets the portal’s rules. Crop it appropriately, use a well-lit image, and resize it to the required dimensions before compressing.' }, { question: 'Should I upload JPG or PNG?', answer: 'Follow the portal’s accepted formats. JPG is usually the smaller choice for a photographic headshot.' }]} />; }
